mysql:
    image: mysql
    container_name: boletines_mysql
    ports:
        - "3306:3306"
    volumes:
        - ./var/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=qwerty
        - MYSQL_DATABASE=boletines
